config/routes.rb
Rails.application.routes.draw do
  resources :videos

  root 'videos#index'
  get 'pages/about'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord

	def next
		Video.where('id>?' , id).first
	end
	def previous
		Video.where('id<?' , id).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  	
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all
    @nextVideo = @video.next
    @previousVideo = @video.previous 
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description , :title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          
  </head>

  <body>
  	<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">videOHLIC</a>
      <a href="<%= videos_path %>" data-activates="mobile-demo" class="button-collapse"><i class="material-icons"></i></a>
      <ul class="right hide-on-med-and-down">
      	<!-- <li><a href="#"><i class="material-icons">apps</i></li> -->
        <li><a href=" <%= videos_path %>"><i class="material-icons">apps</i></a></li>
         <li><a href="<%= pages_contact_path %>"><i class="material-icons">contacts</i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="material-icons">accessibility</i></a></li>

      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#"><i class="material-icons">apps</i></li>
        <li><a href="<%= pages_contact_path %>"><i class="material-icons">contacts</i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="material-icons">accessibility</i></a></li>
      </ul>
    </div>
  </nav>
  <div class="row">
  	<div class="col m10 offset-m1">
  		<%= yield %>	
  	</div>
  </div>
    

    <script>
    	$( document ).ready(function(){
    		$(".button-collapse").sideNav();	
    	})
    	

    </script>
  </body>
</html>

app/views/pages/about.html.erb
<h3>Rohan Arora</h3>

	<div class="card-content white-text">
		<div class="col m6 ">
			<a class="twitter-grid" href="https://twitter.com/TwitterDev/timelines/539487832448843776?ref_src=twsrc%5Etfw">National Park Tweets</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
		</div>
		<div class="col m6">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m3">
						<%= image_tag "rohan.jpg" , class: "circle responsive-img"%>
					</div>
					<div class="col m9">
						<div class="black-text">
							i dont know what to say . Let you know my likes or deslikes .
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/pages/contact.html.erb
<h2>Contact Me !!</h2>

		<div class="col offset-6"><h1>Do you wanna talk . Find me and we could have some drinks.</h1></div>
		<br>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3502.2832665040373!2d77.09001601446603!3d28.62127119134267!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d04afb8dbcfe1%3A0xaff19e718be2136b!2sMaharaja+Surajmal+Group+of+Institutions!5e0!3m2!1sen!2sin!4v1518810039961" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
   <%= form.text_field :wistia, id: :video_wistia , :placeholder => 'Link' , :length => '10' %>
  </div>
  <div class="input-field">
   <%= form.text_field :title , :placeholder => 'title' , :length => '20'%>
  </div>
  <div class="input-field">
   <%= form.text_field :type , :placeholder => 'type' , :length => '20'%>
  </div>
  <div class="input-field">
    <%= form.text_area :description, id: :video_description , :placeholder => 'description' , :length => '800' , :class => 'materialize-textarea' %>
  </div>
  <button class = "btn waves-effect waves-light" , type= 'submit' , name='action'>Submit</button>
  <a href="<%= videos_path %>" , class = "btn waves-effect waves-light"  , name ='action'>Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form', video: @video %>		
	</div>
</div>

app/views/videos/index.html.erb
<p class="notice"><%= notice %></p>

<h1>Listing Videos</h1>
<%= link_to new_video_path , :class => 'btn-floating btn-large waves-effect waves-light red' do %>
<i class="material-icons">add</i>
<% end %>

<ul class="collapsible" data-collapsible="accordion">
  <% @videos.each do |video| %>
    <li>
      <div class="collapsible-header">
       <i class="material-icons">all_inclusive</i>
        <%= link_to video.title , video %>
        <div class="right-position">
          <%= link_to edit_video_path(video) do %>
           <i class="material-icons">build</i>
          <% end %>
          <%= link_to video ,  method: :delete , data: {confirm: 'are you sure'} do %>
            <i class="material-icons">clear</i>
          <% end %>
        </div>
      </div>
      <div class="collapsible-body"><span><%= video.description%></span></div>
    </li>
    <% end %>
  </ul>
        

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form', video: @video %>		
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col m3">
		<div class="collection">
        <% @videos.each do |video| %>
        	<%= link_to video.title , video , :class => 'collection-item' %>
        <% end %> 
      </div>
	</div>
	<div class="col m9">
        <div class="col s12">
          <div class="card blue-grey darken-1">
          	<div class="card-image">
          		<div class="wistia_embed wistia_<%= @video.wistia%> " , style="height:360px">&nbsp;</div>	
          	</div>
          	
          	<div class="card-content white-text">
              <span class="card-title"><%= @video.title%></span>
              <p><%=@video.description%></p>
            </div>
            <div class="card-action">
              <%= link_to "PREVIOUS" , @previousVideo if !@previousVideo.nil? %>
              <%= link_to "NEXT" , @nextVideo if !@nextVideo.nil? %>
            </div>
          </div>
        </div>
	</div>	
</div>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<script >
	wistiaEmbed = Wistia.embed("<%= @video.wistia%> ",{
		videoQuality: "hd-only",
		videoFoam: true
	});
</script>